framework:
    secret: '%env(APP_SECRET)%'

    trusted_hosts: ~

    csrf_protection: true
    http_method_override: true
    esi: true
    fragments: true
#    ide: '%env(FRAMEWORK_IDE)%'

    php_errors:
        log: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_lifetime: 604800 # 1 неделя
#        cookie_samesite: lax

    validation:
        enable_annotations: true
