version: '3.8'

services:
    nginx:
        build:
            context: ./.docker/nginx
            #args:
            #   APP_ENV: '1234'
        working_dir: /app
        volumes:
            - ./:/app
            #- ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-fpm
#        environment: # @todo
#            VIRTUAL_HOST: kopnik2
#            NGINX_HOST: kopnik2
        ports:
            - '${WEB_PORT}:80'
    php-fpm:
        environment:
            APP_ENV: test
            APP_DEBUG: 1
    php-cli:
        environment:
            APP_ENV: test
            APP_DEBUG: 1
