version: '3.8'

services:
    php-fpm:
        ports:
            - 127.0.0.1:9080:9000
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
    php-cli:
        environment:
            APP_ENV: prod
            APP_DEBUG: 0
