version: '3.7'
services:
    kopnik-nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - kopnik-php-fpm
        ports:
            - "8080:80"
    kopnik-php-fpm:
        build:
            context: ./.docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - kopnik-postgres
    kopnik-php-cli:
        build:
            context: ./.docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - kopnik-postgres
    kopnik-postgres:
        image: postgres:12.1-alpine
        volumes:
            - kopnik-postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: app
        ports:
            - "54321:5432"
volumes:
    kopnik-postgres:
    composer:
