version: '3.7'
services:
    nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./.docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        depends_on:
            - db
    php-cli:
        build:
            context: ./.docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        depends_on:
            - db
    db:
        image: postgres:12.1-alpine
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: kopnik
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: kopnik
        ports:
            - "54321:5432"
volumes:
    db:
    composer:
