version: '3.7'
services:
    nginx:
        build:
            context: ./.docker/development
            dockerfile: nginx.docker
        volumes:
            - ./:/app
        depends_on:
            - php-fpm
        ports:
            - "8080:80"
    php-fpm:
        build:
            context: ./.docker/development
            dockerfile: php-fpm.docker
        volumes:
            - ./:/app
        environment:
            APP_ENV: dev
            DATABASE_URL: 'pgsql://kopnik:1234@db:5432/kopnik'
        depends_on:
            - db
    php-cli:
        build:
            context: ./.docker/development
            dockerfile: php-cli.docker
        volumes:
            - ./:/app
            - composer:/root/.composer/cache
        environment:
            DATABASE_URL: 'pgsql://kopnik:1234@db:5432/kopnik'
        depends_on:
            - db
    db:
        build:
            context: ./.docker/development
            dockerfile: postgres.docker
        restart: unless-stopped # always
        environment:
            POSTGRES_USER: kopnik
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: kopnik
        volumes:
#            - ./var/db:/var/lib/postgresql/data
            - kopnik-db:/var/lib/postgresql/data
        ports:
            - "5432:5432"
volumes:
    composer:
    kopnik-db:
