
login_check_vkontakte:
    path: /login/check-vk
#    schemes: [https]

#login_check_github:
#    path: /login/check-github

security_logout:
    path: /api/logout

# @deprecated
#client_rewrite:
#    path: /{slug<.+>}
#    controller: \App\Controller\DefaultController::index
