imports:
    - { resource: "_local.test.yaml", ignore_errors: true }

services:
    App\Tests\Controller\:
        resource: '../tests/Controller'
        tags: ['controller.service_arguments']

    App\Service\VkService: 'App\Tests\Service\VkService'
